import { useState } from 'react'
import heroImage from './assets/hero.avif'

const services = [
  ['01', 'Ghostwriting', 'Your memories, expertise, or big idea shaped into a compelling manuscript that still sounds like you.'],
  ['02', 'Book Editing', 'Thoughtful developmental editing, copyediting, and proofreading that make every page shine.'],
  ['03', 'Book Publishing', 'Beautiful print and ebook production, ISBN support, and worldwide distribution.'],
  ['04', 'Amazon Publishing', 'A polished Amazon presence that helps readers discover your book and buy with confidence.'],
  ['05', 'Book Marketing', 'Smart launch plans and author marketing designed to put your book in front of its readers.'],
  ['06', 'Cover Design', 'Genre-aware covers and interior layouts that look at home on any bookstore shelf.'],
]

const books = [
  ['A Quiet Morning', 'Memoir', 'bg-[#13374a] text-[#e8c99b] border-[#e8c99b]'],
  ['The Last Wild Place', 'Fiction', 'bg-gradient-to-br from-[#d87956] to-[#762e42] text-[#fff8e8]'],
  ['Built to Begin', 'Business', 'bg-[#d8d7b2] text-[#183748]'],
  ['Where the Map Ends', 'Adventure', 'bg-[#302d55] text-[#eab968]'],
]

const faqs = [
  ['What does a full-service publishing partner do?', 'We support the complete journey from a rough idea or finished manuscript through editing, design, production, distribution, and launch planning.'],
  ['Will I keep ownership of my book?', 'Yes. Your work, rights, and royalties stay with you. We are your creative and publishing partner.'],
  ['Can you help if I only have an idea?', 'Absolutely. Our ghostwriting and book-development services are built for authors starting with notes, stories, expertise, or a vision.'],
  ['How do I begin?', 'Share a little about your project through our inquiry form. We will arrange a no-pressure conversation about your goals and next steps.'],
]

const eyebrow = 'font-[DM_Mono] text-[11px] uppercase tracking-[.14em] text-[#cf775e]'
const title = 'font-[Playfair_Display] font-semibold tracking-[-.055em] leading-[.98] text-[#102c3d]'
const button = 'inline-flex items-center gap-5 bg-[#4768d7] px-5 py-4 font-[DM_Mono] text-[11px] font-medium uppercase tracking-wide text-[#102c3d] transition hover:bg-[#cf775e]'

function Logo() {
  return <a className="inline-flex items-baseline font-[Playfair_Display] text-[26px] font-bold tracking-[-.06em] text-[#102c3d]" href="#top"><span className="text-[#cf775e]">dream</span>books<small className="ml-1.5 font-[DM_Mono] text-[8px] tracking-[.21em]"> PUBLISHING</small></a>
}

function App() {
  const [openFaq, setOpenFaq] = useState(0)
  const [menuOpen, setMenuOpen] = useState(false)

  return <>
    <div className="flex min-h-10 items-center justify-center gap-7 bg-[#092637] px-5 py-2 font-[DM_Mono] text-[11px] tracking-wide text-[#dbe0d4] sm:justify-end sm:px-[5vw]"><span className="mr-auto hidden sm:block">For stories that deserve to be read</span><a href="tel:+18005550198">(800) 555-0198</a><a className="text-[#4768d7]" href="#contact">Talk to our team ↗</a></div>
    <header className="relative z-20 flex h-[86px] items-center justify-between bg-[#f7f2e9] px-5 sm:px-[5vw]">
      <Logo />
      <button className="text-3xl text-[#102c3d] md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? '×' : '☰'}</button>
      <nav className={`${menuOpen ? 'flex' : 'hidden'} absolute left-0 right-0 top-[86px] flex-col items-start gap-6 bg-[#f7f2e9] p-6 shadow-lg md:static md:flex md:flex-row md:items-center md:gap-7 md:bg-transparent md:p-0 md:shadow-none`}>
        {['Services', 'Our Process', 'Portfolio', 'About Us'].map((item) => <a className="text-[13px] hover:text-[#cf775e]" href={`#${item === 'Our Process' ? 'process' : item === 'About Us' ? 'about' : item.toLowerCase()}`} onClick={() => setMenuOpen(false)} key={item}>{item}</a>)}
        <a className="w-full bg-[#102c3d] px-5 py-4 text-center font-[DM_Mono] text-[11px] uppercase tracking-wide text-white md:w-auto" href="#contact" onClick={() => setMenuOpen(false)}>Get a free quote</a>
      </nav>
    </header>
    <main id="top">
      <section className="relative isolate min-h-[690px] overflow-hidden text-white" style={{ '--hero-background': `url(${heroImage})` }}>
        <div className="absolute -inset-1 -z-20 bg-[image:var(--hero-background)] bg-cover bg-center blur-[1.5px]" />
        <div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#092637]/78 to-[#092637]/35" />
        <div className="mx-auto grid w-full max-w-[1190px] items-center gap-10 px-5 py-16 sm:px-8 lg:min-h-[690px] lg:grid-cols-[minmax(0,1.2fr)_minmax(380px,.8fr)] lg:gap-14 lg:py-12">
          <div className="max-w-[650px]">
            <p className={`${eyebrow} mb-5 text-[#4768d7]`}>Your story has a place in the world</p>
            <h1 className="max-w-[650px] font-[DM_Sans] text-[clamp(2rem,3vw,2.65rem)] font-medium uppercase leading-[1.14] tracking-[-.025em] text-white">The Book Publishing Company That Helps Authors Publish With Confidence</h1>
            <p className="mt-5 max-w-[630px] font-[DM_Sans] text-[15px] leading-[1.55] text-[#dae2df]">You wrote the words. We handle everything else, writing support, editing, design, publishing, and marketing, so your book launches like one from a top publishing house, not a hopeful first attempt.</p>
            <div className="mt-8 flex flex-wrap items-center gap-x-7 gap-y-5"><a className={`${button} min-h-12 justify-center px-6 py-3 text-center`} href="#contact">Start your publishing journey <b className="text-lg font-normal">→</b></a><a className="border-b border-white pb-1.5 font-[DM_Mono] text-[11px] uppercase tracking-wide" href="#services">Explore our services ↓</a></div>
          </div>
          <div className="relative mx-auto w-full max-w-[460px] lg:ml-auto">
            <form className="relative rounded-[20px] border border-[#4768d7] bg-[#092637]/75 px-6 pb-7 pt-8 shadow-[0_24px_65px_rgba(0,0,0,.35)] backdrop-blur-[3px] sm:px-7" onSubmit={(event) => event.preventDefault()}>
              <span aria-hidden="true" className="absolute -left-3 -top-7 select-none text-5xl text-[#4768d7] drop-shadow-[0_0_18px_#4768d7]">✦</span><span aria-hidden="true" className="absolute -right-3 -top-7 select-none text-5xl text-[#4768d7] drop-shadow-[0_0_18px_#4768d7]">✦</span>
              <h2 className="text-center font-[DM_Sans] text-[22px] font-bold leading-tight">Sign Up and Get Special</h2>
              <p className="mx-auto mt-3 w-fit rounded-full border-2 border-[#4768d7] px-3 py-1 text-center font-[DM_Sans] text-[clamp(1rem,2vw,1.35rem)] font-bold leading-tight text-[#4768d7]">50% Anniversary DISCOUNT</p>
              <div className="mt-6 space-y-3.5">
                <label className="flex h-11 items-center gap-3 rounded border border-white/35 bg-[#092637]/20 px-3 text-[#4768d7] focus-within:border-[#4768d7]"><span aria-hidden="true">♙</span><input aria-label="Your name" className="w-full bg-transparent text-sm text-white outline-none placeholder:text-[#dbe0d4]/70" placeholder="Type Your Name" required /></label>
                <label className="flex h-11 items-center gap-3 rounded border border-white/35 bg-[#092637]/20 px-3 text-[#4768d7] focus-within:border-[#4768d7]"><span aria-hidden="true">✉</span><input aria-label="Your email address" className="w-full bg-transparent text-sm text-white outline-none placeholder:text-[#dbe0d4]/70" placeholder="Type Your Email Address" type="email" required /></label>
                <label className="flex h-11 items-center gap-3 rounded border border-white/35 bg-[#092637]/20 px-3 text-[#4768d7] focus-within:border-[#4768d7]"><span aria-hidden="true">◉</span><input aria-label="Your phone number" className="w-full bg-transparent text-sm text-white outline-none placeholder:text-[#dbe0d4]/70" placeholder="Type Your Phone Number" type="tel" /></label>
                <label className="flex items-start gap-3 rounded border border-white/35 bg-[#092637]/20 px-3 py-3 text-[#4768d7] focus-within:border-[#4768d7]"><span aria-hidden="true" className="mt-0.5">▤</span><textarea aria-label="What you are looking for" className="min-h-[88px] w-full resize-none bg-transparent text-sm text-white outline-none placeholder:text-[#dbe0d4]/70" placeholder="I am looking for..." /></label>
              </div>
              <button className="mt-5 w-full rounded bg-[#4768d7] py-3 font-medium text-white transition hover:bg-[#cf775e]" type="submit">Activate Now</button>
            </form>
          </div>
        </div>
      </section>
      <section id="about" className="grid gap-8 bg-[#e8dfcf] px-5 py-9 sm:grid-cols-[1fr_2.5fr] sm:px-[6vw]"><p className="max-w-[220px] font-[Playfair_Display] text-lg font-medium leading-snug text-[#102c3d]">Trusted by first-time authors, seasoned storytellers, and bright new voices.</p><div className="grid grid-cols-2 gap-y-6 sm:grid-cols-4">{[['500+','Books brought to life'],['12+','Years of creative craft'],['98%','Authors who recommend us'],['40+','Countries reached']].map(([number,label]) => <div className="border-l border-[#102c3d]/20 px-4 sm:px-6" key={label}><strong className="block font-[Playfair_Display] text-4xl text-[#102c3d]">{number}</strong><small className="font-[DM_Mono] text-[10px] uppercase leading-tight text-[#102c3d]">{label}</small></div>)}</div></section>
      <section className="px-5 py-20 text-center sm:px-[8vw] sm:py-32"><p className={eyebrow}>A publishing partner, not just a service</p><h2 className={`${title} mt-5 text-5xl sm:text-7xl`}>Big publishing expertise.<br /><em className="font-medium text-[#4768d7]">Human-scale care.</em></h2><div className="mx-auto mt-10 grid max-w-3xl gap-7 text-left text-[15px] leading-7 text-[#455a64] sm:grid-cols-2 sm:gap-14"><p>Every author arrives with something different: a story that has waited years to be told, a finished manuscript looking for its audience, or an idea that needs a little help finding its shape.</p><p>We bring writers, editors, designers, and publishing specialists together around one goal — making a book you will be proud to put your name on.</p></div></section>
      <section id="services" className="bg-[#e6e8df] px-5 py-20 sm:px-[8vw] sm:py-32"><div className="mb-12 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className={eyebrow}>What we do</p><h2 className={`${title} mt-5 text-5xl sm:text-7xl`}>Everything your<br /><em className="font-medium text-[#4768d7]">book needs.</em></h2></div><a className="w-fit border-b border-[#102c3d] pb-1.5 font-[DM_Mono] text-[11px] uppercase tracking-wide" href="#contact">See all services →</a></div><div className="grid border-l border-t border-[#102c3d]/20 sm:grid-cols-2 lg:grid-cols-3">{services.map(([num, name, copy]) => <article className="group relative min-h-[300px] border-b border-r border-[#102c3d]/20 p-6 transition hover:-translate-y-1 hover:bg-[#102c3d] hover:text-white" key={name}><span className="font-[DM_Mono] text-[10px]">{num}</span><div className="mt-10 text-3xl text-[#cf775e]">✦</div><h3 className="mt-4 font-[Playfair_Display] text-2xl font-semibold">{name}</h3><p className="mt-2 max-w-xs text-[13px] leading-5 text-[#51616a] group-hover:text-[#d1dad3]">{copy}</p><a className="absolute bottom-6 font-[DM_Mono] text-[10px] uppercase" href="#contact">Discover more ↗</a></article>)}</div></section>
      <section id="process" className="grid gap-12 bg-[#092637] px-5 py-20 text-white sm:px-[8vw] sm:py-32 lg:grid-cols-2 lg:gap-[9vw]"><div><p className={`${eyebrow} text-[#4768d7]`}>How it works</p><h2 className="mt-5 font-[Playfair_Display] text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl">Your idea.<br />Our craft.<br /><em className="font-medium text-[#4768d7]">A book to love.</em></h2><p className="mt-6 max-w-md leading-7 text-[#c8d3ce]">No mysteries, no industry maze. Just a clear, collaborative path from the first conversation to the day you hold your finished book.</p><a className="mt-7 inline-flex bg-[#f7f2e9] px-5 py-4 font-[DM_Mono] text-[11px] uppercase tracking-wide text-[#102c3d]" href="#contact">Tell us about your book →</a></div><ol>{[['01','Share your story','Tell us where your book is now and where you want it to go.'],['02','Create with confidence','Your dedicated team shapes, refines, and designs every detail.'],['03','Publish beautifully','We prepare your book for the world — in print, digital, and audio.'],['04','Find your readers','Launch with a strategy made for the people your story was written for.']].map(([n, name, copy]) => <li className="grid grid-cols-[65px_1fr] border-t border-white/25 py-6" key={n}><span className="font-[DM_Mono] text-[11px] text-[#4768d7]">{n}</span><div><h3 className="font-[Playfair_Display] text-2xl">{name}</h3><p className="mt-2 text-sm leading-6 text-[#c4d0c9]">{copy}</p></div></li>)}</ol></section>
      <section className="px-5 py-20 text-center sm:px-[8vw] sm:py-32"><p className={eyebrow}>Stories of every kind</p><h2 className={`${title} mt-5 text-5xl sm:text-7xl`}>Whatever you write,<br /><em className="font-medium text-[#4768d7]">we know its language.</em></h2><div className="mt-10 grid border-l border-t border-[#102c3d]/20 text-left sm:grid-cols-2 lg:grid-cols-4">{['Fiction','Memoir','Self-Help','Business','Children’s Books','Biography','Poetry','Cookbooks'].map((genre, index) => <div className="flex items-center gap-3 border-b border-r border-[#102c3d]/20 p-5 font-[Playfair_Display] text-xl" key={genre}><span className="font-[DM_Mono] text-[9px] text-[#cf775e]">0{index + 1}</span>{genre}<b className="ml-auto font-sans text-sm">↗</b></div>)}</div></section>
      <section id="portfolio" className="bg-[#e8dfcf] px-5 py-20 sm:px-[8vw] sm:py-32"><div className="mb-12 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className={eyebrow}>Selected work</p><h2 className={`${title} mt-5 text-5xl sm:text-7xl`}>Made to be<br /><em className="font-medium text-[#4768d7]">picked up.</em></h2></div><a className="w-fit border-b border-[#102c3d] pb-1.5 font-[DM_Mono] text-[11px] uppercase" href="#contact">View the full portfolio →</a></div><div className="grid grid-cols-2 gap-5 lg:grid-cols-4">{books.map(([name, type, colors]) => <article key={name}><div className={`flex aspect-[.68] flex-col items-center justify-between p-5 text-center shadow-xl transition hover:-translate-y-2 ${colors}`}><span className="font-[DM_Mono] text-[9px] uppercase tracking-widest">{type}</span><strong className="font-[Playfair_Display] text-3xl leading-none">{name}</strong><i className="font-[DM_Mono] text-[9px] uppercase tracking-widest">Dream Books</i></div><h3 className="mt-4 font-[Playfair_Display] text-xl font-semibold text-[#102c3d]">{name}</h3><p className="mt-1 font-[DM_Mono] text-[10px] uppercase text-[#6c7170]">{type}</p></article>)}</div></section>
      <section className="bg-[#cf775e] px-[8%] py-20 text-center text-[#fff9ec] sm:py-32"><div className="font-[Playfair_Display] text-8xl leading-none">“</div><blockquote className="mx-auto mt-4 max-w-5xl font-[Playfair_Display] text-3xl font-medium leading-tight sm:text-5xl">Dream Books Publishing listened to the heart of my story, then helped me turn it into a book I did not think was possible.</blockquote><p className="mt-7 font-[DM_Mono] text-[10px] tracking-widest">— ELENA R., MEMOIR AUTHOR</p></section>
      <section className="grid gap-12 px-5 py-20 sm:px-[8vw] sm:py-32 lg:grid-cols-[.85fr_1.15fr] lg:gap-[10vw]"><div><p className={eyebrow}>Answers, clearly told</p><h2 className={`${title} mt-5 text-5xl sm:text-6xl`}>Questions from<br /><em className="font-medium text-[#4768d7]">future authors.</em></h2><p className="mt-6 max-w-sm leading-7 text-[#52616a]">Publishing is a big step. We make sure you know exactly what it looks like.</p></div><div className="border-t border-[#102c3d]/20">{faqs.map(([question, answer], index) => <article className="border-b border-[#102c3d]/20" key={question}><button className="flex w-full justify-between py-6 text-left font-[Playfair_Display] text-xl text-[#102c3d]" onClick={() => setOpenFaq(openFaq === index ? -1 : index)}>{question}<b className="font-sans text-2xl font-normal text-[#cf775e]">{openFaq === index ? '−' : '+'}</b></button>{openFaq === index && <p className="mb-6 mr-8 text-sm leading-7 text-[#53636a]">{answer}</p>}</article>)}</div></section>
      <section id="contact" className="grid gap-12 bg-[#092637] px-5 py-20 text-white sm:px-[8vw] sm:py-32 lg:grid-cols-2 lg:gap-[10vw]"><div><p className={`${eyebrow} text-[#4768d7]`}>The next chapter starts here</p><h2 className="mt-5 font-[Playfair_Display] text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl">Ready to see your<br /><em className="font-medium text-[#4768d7]">story in print?</em></h2><p className="mt-6 max-w-md leading-7 text-[#c4d0c9]">Tell us a little about your book. A member of our team will be in touch to arrange your free consultation.</p><a className="mt-5 inline-block font-[Playfair_Display] text-2xl text-[#4768d7]" href="tel:+18005550198">(800) 555-0198</a></div><form className="flex flex-col gap-5" onSubmit={(event) => event.preventDefault()}><label className="font-[DM_Mono] text-[10px] uppercase tracking-wide text-[#e9dfce]">Your name<input className="mt-2 block w-full border-0 border-b border-white/40 bg-transparent py-3 text-base outline-none placeholder:text-[#91a09b]" required placeholder="Jane Smith" /></label><label className="font-[DM_Mono] text-[10px] uppercase tracking-wide text-[#e9dfce]">Email address<input className="mt-2 block w-full border-0 border-b border-white/40 bg-transparent py-3 text-base outline-none placeholder:text-[#91a09b]" type="email" required placeholder="jane@email.com" /></label><label className="font-[DM_Mono] text-[10px] uppercase tracking-wide text-[#e9dfce]">Tell us about your book<textarea className="mt-2 block w-full resize-y border-0 border-b border-white/40 bg-transparent py-3 text-base outline-none placeholder:text-[#91a09b]" placeholder="I have an idea for..." rows="4" /></label><button className={`${button} mt-2 w-fit`} type="submit">Request my free consultation →</button><small className="text-[10px] text-[#9ba9a4]">This demo form is frontend-only and does not send data.</small></form></section>
    </main>
    <footer className="grid gap-6 bg-[#061c29] px-5 pb-6 pt-14 text-[#d5dcd4] sm:grid-cols-[1.4fr_1fr_1fr] sm:px-[8vw]"><Logo /><p className="max-w-xs text-[13px] leading-6">Helping authors turn meaningful ideas into beautifully made books.</p><div className="flex flex-wrap gap-x-6 gap-y-3 self-start font-[DM_Mono] text-[10px] uppercase"><a href="#services">Services</a><a href="#process">Process</a><a href="#portfolio">Portfolio</a><a href="#contact">Contact</a></div><small className="border-t border-white/20 pt-5 font-[DM_Mono] text-[10px] sm:col-span-3">© {new Date().getFullYear()} Dream Books Publishing. All rights reserved.</small></footer>
  </>
}

export default App
